### ISSUE TITLE
Teensyduino 1.56 - Snooze not working on T4.x at all

### ISSUE THREAD

**Issue by david-res** [duff2013/Snooze#110]
After further testing, it seems like this library does not work at all on any T4.x (4.0, 4.1, Micromod).
The examples will compile, but when uploading the boot led will flash 9 times.

**Comment by FrankBoesing** [comment]
https://github.com/duff2013/Snooze/pull/111

**Comment by david-res** [comment]
Fixed by setting [function ](https://github.com/duff2013/Snooze/blob/master/src/hal/TEENSY_40/hal.c#L652)
`startup_early_hook` into FLASHMEM
