### ISSUE TITLE
Digital Interrupts not Working for Teensy LC on Sleep

### ISSUE THREAD

**Issue by MarcianoPreciado** [duff2013/Snooze#15]
When trying out the sleep_all_wakeups example code on my Teensy LC the digital interrupts aren't waking the processor from sleep. I switch the 
`#elif defined(__MKL26Z64__)`
`    who = Snooze.sleep( config_teensyLC );// return module that woke processor`
`#endif
`
part for.
`#elif defined(__MKL26Z64__)`
`    who = Snooze.hibernate( config_teensyLC );// return module that woke processor`
`#endif`

and the digital interrupt functionality works just fine.

Edit: It also works fine with deepSleep

**Comment by duff2013** [comment]
Do you have the latest version of Snooze? I have tested the digital wake-ups before for you on the LC and they worked fine for all sleep types i.e.. sleep, deepSleep and hibernate. I'm not sure why yours is not working, what other code and hardware do you have hooked up to the LC? I need to know the details to trouble shoot this.

**Comment by duff2013** [comment]
F.Y.I you got me looking for any bugs in the digital pin driver code and I did find one small one that might effect the LC. While I did test that driver with my LC and it did work I didn't try with all pins so maybe there could be certain pins effected with this bug. I don't have an LC with me now but I went ahead and updated this library.

**Comment by MarcianoPreciado** [comment]
I ran the example sketch and nothing more. Yes, it was the most recent version, and on a bare-bones teensy LC straight out of the packaging.

**Comment by duff2013** [comment]
I don't know, digital wakeups for sleep work just fine with the LC's I have. You ae pulling the wakeup pins to ground to wake right? The example uses Pull-Ups.

**Comment by darianbjohnson** [comment]
@MarcianoPreciado did you ever figure out why this wasn't working for you? I'm having the same problem with my "straight out of the bag" Teensy LC

**Comment by MarcianoPreciado** [comment]
I believe my issue was that I wasn't configuring my pins correctly. They needed to be INPUT_PULLDOWN

**Comment by MarcianoPreciado** [comment]
I'll check my old code to check.

**Comment by MarcianoPreciado** [comment]
```_digital.pinMode(_ackBtn, INPUT_PULLUP, RISING);```
