### ISSUE TITLE
Maximum delay of Timer 

### ISSUE THREAD

**Issue by jyviko** [duff2013/Snooze#23]
Duff,
I am trying to set the timer to fire after 5 minutes (3e5 milliseconds) but I am noticing that fires at maximum after 60 seconds. Is this the limit?
How can I set the module to wake up every 5 minutes?

Thx,
Iraklis

**Comment by duff2013** [comment]
The max time for the timer wakeup is 65355 milliseconds use the rtc driver for longer sleep times.

**Comment by jyviko** [comment]
Thank you Duff. My bad I should have checked better in the manual - LPTMRx_CMR is 16bit. 
The library works perfect - really impressive work considering the complexity of the K20 sleep modes.
