### ISSUE TITLE
How to count interrupts in sleep mode

### ISSUE THREAD

**Issue by ghost** [duff2013/Snooze#29]
Hello.

How can i count interrupts on pins 2 and 3 (simple increments of variables) without losing this information and without the teensy 3.2/LC waking from one of the sleep modes?

Can i change the CPU Prescaler to values lower than 2mHz?

tks, André

**Comment by duff2013** [comment]
I don't think that possible without waking the processor to service the interrupt. 

Yes, but it touches alot of resources to get it to work, [this](https://github.com/duff2013/Snooze/blob/master/utility/clocks.h#L149) is the part of the code that handles the clocks for Snooze. You can also look at the teensyduino core which does all the clock generation stuff [here](https://github.com/PaulStoffregen/cores/blob/master/teensy3/mk20dx128.c#L787), [here](https://github.com/PaulStoffregen/cores/blob/master/teensy3/mk20dx128.c#L835), [here](https://github.com/PaulStoffregen/cores/blob/master/teensy3/mk20dx128.c#L1042), [here](https://github.com/PaulStoffregen/cores/blob/master/teensy3/mk20dx128.c#L1076) and [here](https://github.com/PaulStoffregen/cores/blob/master/teensy3/mk20dx128.c#L1084).
