### ISSUE TITLE
Teensy freezes

### ISSUE THREAD

**Issue by novalex98** [duff2013/Snooze#31]
We are using the deepsleep function with the digital and timer modules imported. Around half the time the teensy 3.5 responds on time to timer wakeups and responds, albeit slowly, to digital wakeups. The other half of the time it just freezes up and we have to use the reset button to make it respond. If it matters, the calls to snooze are being made in a library, not in the main function code. Please help!

**Comment by duff2013** [comment]
Without any offending code I can't help!
