### ISSUE TITLE
Snooze config.pinMode example wrong?

### ISSUE THREAD

**Issue by Erik-k** [duff2013/Snooze#34]
In deepSleep_all_wakeups.ino there are these lines:
`

    // trigger at threshold values greater than 1.65v
    //config.pinMode(11, CMP, HIGH, 1.65);//pin, mode, type, threshold(v)
    // trigger at threshold values less than 1.65v
    compare.pinMode(11, LOW, 1.65);//pin, mode, type, threshold(v)`

But I think those examples are wrong. config.pinMode doesn't seem to exist and pinMode only takes 3 args, not 4. compare.pinMode exists though.

**Comment by duff2013** [comment]
Yes that's a typo, "config" should be "compare" and "CMP" should be removed from the parameters list, thanks for pointing that out I'll fix it on the next update!
