### ISSUE TITLE
deepSleep prevents loading new code?

### ISSUE THREAD

**Issue by Erik-k** [duff2013/Snooze#35]
I'm dealing with an issue where it looks like my Teensy 3.2 is in deepSleep mode (which I put it in) but that turns off the bootloader, and now I can't get any new code loaded on there. I posted the issue on the official pjrc forum:
https://forum.pjrc.com/threads/45544-Teensy-3-2-no-longer-able-to-upload-code-via-Arduino-IDE?p=149695#post149695

Is this a known issue where someone can "lock" themselves out of a Teensy 3.2 by putting it in deepSleep, which turns off the bootloader, which disables loading new code? 

While we're on the topic is there a nice list of all the differences between sleep, deepSleep, and hibernate? I couldn't find anything in the datasheet or chip reference manual that made that clear and going through all the register calls in the code would take a while.

**Comment by duff2013** [comment]
no i should not, can you:
1. open arduino compile the blink example.
2. unplug the usb cable from computer.
3. hold down the program button on the teensy and plug the usb cable back in.
4. release the program button, the teensy loader should upload the blink example.

**Comment by Erik-k** [comment]
I tried that but it doesn't work, the Teensy doesn't even show up on a COM port anymore.

**Comment by duff2013** [comment]
Are you sure your cable is good, have you tried it with other Teensies? Did you have anything connected to the Teensy i.e. sensors, motors, etc.. I have about thrity Teensies and this library has been around for 3 years now and never had sleeping a Teensy result in a bricked Teensy.

**Comment by Erik-k** [comment]
I took the teensy and cable and used it with a new computer that had brand-new installs of Arduino and the Teensy Loader, and it worked. So it must be something I borked on my other computer. :-( ?
