### ISSUE TITLE
Missing kinetis.h?

### ISSUE THREAD

**Issue by jbalanko** [duff2013/Snooze#4]
I've tried to compile the Snooze library in the Arduino IDE, but I get an error that kinetis.h is missing.  This file is referenced in mcg.h and peripheral.h.  Commenting out the #include lines in both these files just causes a number of missing function declarations.  The kinetis.h file seems to be missing from the source code of all available releases (checked 5.0 to 5.5).  Am I missing something?

**Comment by duff2013** [comment]
what version Teensyduino are you using?

**Comment by jbalanko** [comment]
I was running 1.18 IIRC, but I just updated to 1.26 and it compiles now. Thanks!
