### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by becauseinterwebs** [duff2013/Snooze#42]
What is the difference between sleep, deep sleep and hibernate?

Also, I'm assuming when I call the sleep mode in the main loop it blocks the loop until it wakes up?

Thank you!

**Comment by duff2013** [comment]
sleep, deepSleep and hibernate all block. 

So sleep is the most flexable since it doesn't power as much down as deepSleep or hibernate. With sleep any interrupt can wake the Teensy while the other two only certian types of interrupts can wake the teensy.

**Comment by duff2013** [comment]
didn't mean to close this, hit the wrong button :)
