### ISSUE TITLE
Error while using Snooze library on Teensy 3.5

### ISSUE THREAD

**Issue by gnioco** [duff2013/Snooze#45]
Hi,

I'm trying to run the example in "Snooze/examples/sleep/sleep_all_wakeups/sleep_all_wakeups.ino" on Teensy 3.5 board. It compiles fine. However, after I try to run, I get this error in the serial terminal. I'm using Platformio IDE.

`Exception in thread rx: Traceback (most recent call last): File "C:\...\.platformio\python27\Lib\threading.py", line 801, in __bootstrap_inner self.run() File "C:\...\.platformio\python27\Lib\threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs) File "c:\...\.platformio\penv\lib\site-packages\serial\tools\miniterm.py", line 445, in reader data = self.serial.read(self.serial.in_waiting or 1) File "c:\...\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 257, in in_waiting raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError())) SerialException: ClearCommError failed (WindowsError(22, 'The device does not recognize the command.'))`

I also found this answer:

https://forum.pjrc.com/threads/41262-Snooze-hibernate-deepsleep-sleep-not-working-on-Teensy-3-5

I checked my "kinetis.h" file and I already have "#define HAS_KINETIS_LLWU_16CH" on line 548.

Any ideas what went wrong?

Thank you for help,
Regards

**Comment by duff2013** [comment]
I have never used platformio IDE and the error is pretty cryptic to me. I can't see where in Snooze it is having compile issues from the error you posted. Check to see if there is somewhere in the Platformio errors where it refers to Snooze and let me know.

**Comment by gnioco** [comment]
Hi,

It was an error with my installation of the library. I installed it manually and it was wrong.
Now I installed it with Platformio, like its described here: https://platformio.org/lib/show/1570/Snooze/installation

And its working. However, after programming the deepSleep example, I cannot program the Teensy any more. It keeps reseting due to the Low Power Timer wakeup.

Any solutions?

Thank you

**Comment by duff2013** [comment]
Did you press the program button? Anytime you sleep you have to physically push the program button to upload code.

**Comment by gnioco** [comment]
Ok, I managed. Thank you for help.
regards
