### ISSUE TITLE
Multiple Compare Inputs

### ISSUE THREAD

**Issue by j-protex** [duff2013/Snooze#47]
Hey,
is it possible to use more than one pin to wake Teensy 3.6 with the compare-mode? It's said that there are 3 possible pins for compare (4, 9, 11) and I would like to use at least two of them to create something like a comparator by using compare. And which value would "who" have, if I was using for example pin 9 and 11, when the Teensy is either triggered by 9 or 11?

**Comment by duff2013** [comment]
The library only supports a single compare pin at a time but it looks like it could work. Not sure when I could try this but I'll let you know.

**Comment by j-protex** [comment]
Alright, sounds good, thank you so much! Please keep me updated.
