### ISSUE TITLE
RTC not advancing in deepSleep

### ISSUE THREAD

**Issue by cunidev** [duff2013/Snooze#5]
I don't know what can be the cause, or whether this is voluntary and/or needed in order for this library to run, but I notice that the Teensy RTC stops when I put it in deepSleep... And this can cause problems to many applications that need the RTC to run in background. I'm using a Teensy 3.1 board. Thanks in advance.

**Comment by duff2013** [comment]
Assuming you have the crystal installed and your using the stock time library that comes with teensyduino, you need resync (setSyncProvider) the RTC after waking up. Not sure what you mean by not working? I know it works for me after waking but again I have to resync it so the time library is happy.

**Comment by cunidev** [comment]
Thanks, I didn't know I had to resync. What about implementing that by
default in the library, if it's necessary?

**Comment by duff2013** [comment]
I'm currently updating the library anyway so I'll look into that.

**Comment by cunidev** [comment]
Thanks!

**Comment by duff2013** [comment]
I'm going to close this issue.
