### ISSUE TITLE
Teensy 3.2 Pin 16 not working correctly

### ISSUE THREAD

**Issue by boklubre** [duff2013/Snooze#51]
Hi,

I have a cuircit with a Teensy LC. It will be wake up by a alarm interrupt on Pin 16 from a DS3231 (direct connectet). It works perfectly. When I use a Teensy 3.2 on the same cuircit the chip never wake up on an alarm interrupt. It´s possible that the Teensy 3.2 Snooze libery don´t working correct?
Thank for your help.
Boris

**Comment by duff2013** [comment]
Pin 16 should work, have you tried one of the examples using pin 16? Also try it without the DS3231 and just a wire.
