### ISSUE TITLE
SPI gets mismatch and system freeze when entering sleep

### ISSUE THREAD

**Issue by ramonschepers** [duff2013/Snooze#6]
as stated in the title.

the mismatch led lights up (i have set this to be pin 5 in the spi lib), then the whole mcu freezes.

**Comment by duff2013** [comment]
Not sure what is going on here can you post some code that demonstrates this and explain more what you are trying to do and what hardware you are using?

**Comment by duff2013** [comment]
I'm going to close this issue.
