### ISSUE TITLE
Example does not compile with Teensy 3.0

### ISSUE THREAD

**Issue by rroeber** [duff2013/Snooze#65]
Snooze library: 6.3.4
Example program: hibernate_all_wakeups
Arduino version: 1.8.9
Teensy model: 3.0, 48MHz

Issue:
When I "Verify" the example, none of the drivers are recognized:
       'SnoozeDigital' does not name a type
       'SnoozeCompare' does not name a type
        etc.
I looked around in the driver code and it appears that MK20DX128 may not be included in some of the .h files.  For example, in hal/TEENSY_32/SnoozeDigital.h, 
     #if defined(__MK20DX256__)
should probably be
     #if defined(__MK20DX128__) || defined(__MK20DX256__)

Thanks,
R2

**Comment by duff2013** [comment]
Teensy 3.0 is not supported.
