### ISSUE TITLE
No wakeup from Alarm in 6.3.4

### ISSUE THREAD

**Issue by hanpude** [duff2013/Snooze#68]
In 6.3.4 a Teensy 3.5 doesn't wakeup from Alarm. It does wakeup from Timer or e.g. falling edge on a Digital pin. 
In 6.3.2 also the Alarm wakeup works properly, but with this version I don't get the right wakeup source returned.
My environment is:
Teensy 3.5 w crystal and CR2032 battery, Arduino 1.8.9, Teensyduino 1.4.7
Thanks for providing this library, time and effort to maintain it, this is not taken for granted.
H

**Comment by duff2013** [comment]
I just updated Snooze only deepSleep and hibernate work so far you can download [here](https://github.com/duff2013/Snooze/releases/tag/v6.2.5), let me know if you have any problems.
