### ISSUE TITLE
Teensy 4.0

### ISSUE THREAD

**Issue by mbatesole** [duff2013/Snooze#69]
It appears Snooze/src/hal/TEENSY_40/ is missing the appropriate header files: 

#include "SnoozeTimer.h"
#include "SnoozeAlarm.h"
#include "SnoozeTouch.h"
#include "SnoozeCompare.h"
#include "SnoozeDigital.h"
#include "SnoozeAudio.h"
#include "SnoozeUSBSerial.h"
#include "Snoozelc5vBuffer.h"
#include "SnoozeSPI.h"

**Comment by duff2013** [comment]
Yes Teensy 4.0 is not working, I have hope to work on this soon but other things keep getting in my way.

**Comment by HanJ67** [comment]
When can we expect a version for Teensy 4.0 to go to sleep and wakeup via interrupt IO

**Comment by duff2013** [comment]
I've been working on it stay tuned I'll have a beta hopefully in a week.

**Comment by HanJ67** [comment]
Oh great, thanks a lot, really appreciated..

**Comment by HanJ67** [comment]
Hi,
Yesterday I tried the updated lib on a Teensy 4.0 environment and got a compiler error on hal.c. I had not enough time to search for the reason. It should work now, right?
thanks and best regards, han

**Comment by duff2013** [comment]
I'm working on it, should have another beta out by the weekend.

**Comment by HanJ67** [comment]
Works perfectly.....thanks a lot....

**Comment by duff2013** [comment]
Glad to hear going to close this issue then.
