### ISSUE TITLE
Teensy LC does not wake up from on digital interrupt

### ISSUE THREAD

**Issue by darianbjohnson** [duff2013/Snooze#71]
I am having a hard time getting my Teensy LC to wake up (using pins 21 or 22, pin to ground to wake). Using the sleep, deep sleep, and hibernate examples. 

Maybe I'm missing something here. I load the example. Teensy goes to sleep/deepSleep/Hibernate.

I bring pin 21 (or 22) to ground. 

Nothing.

Am I doing something bone-headed here? Seems like it should work. 

Thanks

**Comment by duff2013** [comment]
Not sure can you post code that shows this not working, try to make the code concise as possible.

**Comment by duff2013** [comment]
I just updated Snooze only deepSleep and hibernate work so far you can download [here](https://github.com/duff2013/Snooze/releases/tag/v6.2.5), let me know if you have any problems.

**Comment by darianbjohnson** [comment]
Thanks; I'll test and report back if there are issues.
