### ISSUE TITLE
Snooze works on Teensy 3.5 but not on Teensy 3.2

### ISSUE THREAD

**Issue by andrewashe** [duff2013/Snooze#73]
Hi I have used snooze with Teensy 3.5 and it works perfectly with simple code below.  Same code doesnt work on Teensy 3.2. (teensy goes to sleep and never wakes up). Any thoughts?
`#include <Snooze.h>

const int led = 13;
// Load timer driver
SnoozeTimer timer;
// install timer driver to a SnoozeBlock
SnoozeBlock config(timer);

void setup()
{

  Serial.begin(9600);
  pinMode(led, OUTPUT);
  timer.setTimer(5000);

}

void loop()
{
  digitalWrite(led, HIGH);
  delay (3000);
  digitalWrite(led, LOW);
  Snooze.deepSleep(config);
}`

**Comment by duff2013** [comment]
I just updated Snooze only deepSleep and hibernate work so far you can download [here](https://github.com/duff2013/Snooze/releases/tag/v6.2.5), let me know if you have any problems.
