### ISSUE TITLE
Teensy 4 Audio

### ISSUE THREAD

**Issue by becauseinterwebs** [duff2013/Snooze#90]
Upgrading a project using the audio adapter from Teensy 3.2 to Teensy 4.  Looks like the support for Teensy 4 no longer has SnoozeAudio?  I commented out the audio config lines but my app hangs after it plays a .WAV file.  Is this no longer needed for Teensy 4?  Thank you!

**Comment by duff2013** [comment]
Not sure what is needed for the T4.x audio with Snooze, I'll try to look at it for the next update.

**Comment by jyviko** [comment]
Any news on the audio driver for the Teensy 4.0/4.1?
